name: setup

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: npm ci
      - run: npm test
      name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${ 4d73005b-574b-4b77-bb43-63945e56b956 }
      - run: make setup
      - run: make test
      - run: make lint
