name: setup

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${ 4d73005b-574b-4b77-bb43-63945e56b956 }
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: make setup
      - run: make test
      - run: make lint
